// <auto-generated />
using System;
using FinanceManager.Account;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceManager.Account.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231014144531_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceManager.Account.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceManager.Account.Models.AccountLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("LimitValue")
                        .HasColumnType("numeric");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AccountLimits");
                });

            modelBuilder.Entity("FinanceManager.Account.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Transfer",
                            RequestId = "00000000-0000-0000-0000-000000000001",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Salary",
                            RequestId = "00000000-0000-0000-0000-000000000002",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Bank",
                            RequestId = "00000000-0000-0000-0000-000000000003",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Return",
                            RequestId = "00000000-0000-0000-0000-000000000004",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Part time job",
                            RequestId = "00000000-0000-0000-0000-000000000005",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Rent",
                            RequestId = "00000000-0000-0000-0000-000000000006",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Other",
                            RequestId = "00000000-0000-0000-0000-000000000007",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Food",
                            RequestId = "00000000-0000-0000-0000-000000000008",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Home",
                            RequestId = "00000000-0000-0000-0000-000000000009",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Transport",
                            RequestId = "00000000-0000-0000-0000-000000000010",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Personal",
                            RequestId = "00000000-0000-0000-0000-000000000011",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Services",
                            RequestId = "00000000-0000-0000-0000-000000000012",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Rest",
                            RequestId = "00000000-0000-0000-0000-000000000013",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Education",
                            RequestId = "00000000-0000-0000-0000-000000000014",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Beauty",
                            RequestId = "00000000-0000-0000-0000-000000000015",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Low",
                            RequestId = "00000000-0000-0000-0000-000000000016",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Name = "Grocery",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            RequestId = "00000000-0000-0000-0000-000000000017",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Name = "Pub",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            RequestId = "00000000-0000-0000-0000-000000000018",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Name = "Delivery",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            RequestId = "00000000-0000-0000-0000-000000000019",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Name = "Restaurant",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000008"),
                            RequestId = "00000000-0000-0000-0000-000000000020",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Name = "Repair",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            RequestId = "00000000-0000-0000-0000-000000000021",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Name = "Rent",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            RequestId = "00000000-0000-0000-0000-000000000022",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Name = "Furniture",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            RequestId = "00000000-0000-0000-0000-000000000023",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Name = "Electrical appliances",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000009"),
                            RequestId = "00000000-0000-0000-0000-000000000024",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Name = "Public transport",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequestId = "00000000-0000-0000-0000-000000000025",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Name = "Taxi",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequestId = "00000000-0000-0000-0000-000000000026",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Name = "Airplane",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequestId = "00000000-0000-0000-0000-000000000027",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Name = "Train",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RequestId = "00000000-0000-0000-0000-000000000028",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FinanceManager.Account.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
