name: .NET

on:
  push:
    branches: [ "main" ]
    #TODO: create src, common, tests folders 
    paths:
     - "FinanceManager.Account/**"
     - "FinanceManager.Account.Tests/**"
     - "FinanceManager.Events/**"
     - "FinanceManager.Testing/**"
     - "FinanceManager.TransportLibrary/**"
     - "FinanceManager.UnitOfWork/**"
     - "FinanceManager.Web/**" 
  pull_request:
    branches: [ "main" ]
    paths:
      - "FinanceManager.Account/**"
      - "FinanceManager.Account.Tests/**"
      - "FinanceManager.Events/**"
      - "FinanceManager.Testing/**"
      - "FinanceManager.TransportLibrary/**"
      - "FinanceManager.UnitOfWork/**"
      - "FinanceManager.Web/**"

env:
  project-file: "./FinanceManager.Account/FinanceManager.Account.csproj"
  test-project-file: "./FinanceManager.Account.Tests/FinanceManager.Account.Tests.csproj"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.project-file }}

    - name: Build
      run: dotnet build --no-restore ${{ env.project-file }}

    - name: Test
      run: dotnet test ${{ env.test-project-file }}

    - name: Download Sonar Scanner
      run: |
        curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-windows-x64.zip -OutFile sonar-scanner-cli-6.1.0.4477-windows-x64.zip

    - name: Extract Sonar Scanner
      run: |
        tar -xf sonar-scanner-cli-6.1.0.4477-windows-x64.zip

    - name: Run SonarQube Scan
      run: |
        ./sonar-scanner-6.1.0.4477-windows-x64/bin/sonar-scanner.bat -D"sonar.token=${{ secrets.SONAR_TOKEN }}" -D"sonar.projectKey=FinanceManager" -D"sonar.sources=./FinanceManager.Account" -D"sonar.host.url=http://localhost:9000"